spring.application.name=GoSchool
spring.datasource.url=jdbc:postgresql://localhost:5432/go-school
spring.datasource.username=postgres
spring.datasource.password=Letsdoit!
#spring.datasource.driver-class-name=org.postgresql.Driver

#JPA configuration

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.jpa.open-in-view=true

# Serve static files from uploads directory
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.upload-dir}/
#Server configuration,
#server.address=0.0.0.0
server.port=8080
jwt.expirationMs= 86400000

jwt.secret=MySuperSecretJwtKeyThatIsLongEnough123!
file.upload-dir=uploads/

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
#logging.level.root=DEBUG

#Email Services
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seetsi1997@gmail.com
spring.mail.password=ytzocfdlbucomknk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true


